
###

http://localhost:3031

###

https://servis.nikolav.rs

###

POST http://localhost:3031/graphql
Accept: application/json
Content-Type: application/json

{
  "query": "{ status }"
}

###

POST http://localhost:3031/graphql
Accept: application/json
Content-Type: application/json

{
  "query": "mutation { demo(data: { foo: \"bar\" }) }"
}

###

